### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by st2yang** [matwilso/object_collections#1]
Hi,

Thanks for your great work! And I am trying to reproduce/benchmark your results. Would you mind sharing the pre-trained models for evaluation?

Thanks,
Yang

**Comment by matwilso** [comment]
Hi, sorry, I don't have the pre-trained weights anymore.  I had to clean a bunch of stuff off my hard drive awhile ago.

**Comment by st2yang** [comment]
Sure, I'll try to train the models on my own.

I tried to install the environment properly but encountered one issue while running the scripts. Can you help a little? I am wondering how you set up the bashrc to run the scripts?

I can run with standard mujoco/gym environments. But when I run your scripts, it raises the following errors. It looks like the issue here [mujoco issue](https://github.com/openai/mujoco-py/issues/187). But I haven't properly set up my bashrc so far. I also attached my bashrc below.

Thanks,
Yang

**bashrc**
> export LD_LIBRARY_PATH=/homes/yangyang/.mujoco/mujoco200/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
> export MUJOCO_KEY_PATH=/homes/yangyang/.mujoco${MUJOCO_KEY_PATH}
> export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-000
> 

**running data_collections scripts**
> running algorithm
> Found 1 GPUs for rendering. Using device 0.
> Found 1 GPUs for rendering. Using device 0.
> Could not make EGL context current
> Found 1 GPUs for rendering. Using device 0.
> Could not make EGL context current
> Exception in thread Thread-2:
> RuntimeError: Failed to initialize OpenGL
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/rl/trainer.py", line 548, in rollout_maker
>     rollouts = self.roller.rollouts()
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/rl/rollers.py", line 212, in rollouts
>     self.reset()
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/rl/rollers.py", line 202, in reset
>     self._last_obs.append(self.batched_env.reset_wait(sub_batch=i))
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/site-packages/anyrl/envs/base.py", line 207, in reset_wait
>     obses.append(env.reset_wait())
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/site-packages/anyrl/envs/gym.py", line 108, in reset_wait
>     res = self._decode_observation(self._get_response())
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/site-packages/anyrl/envs/gym.py", line 145, in _get_response
>     raise RuntimeError('exception on worker') from resp_obj
> RuntimeError: exception on worker
> 
> Could not make EGL context current
> 

**running the evaluation script**
> Found 1 GPUs for rendering. Using device 0.
> Could not make EGL context current
> Traceback (most recent call last):
>   File "./eval_main.py", line 102, in <module>
>     main()
>   File "./eval_main.py", line 99, in main
>     eval_policy()
>   File "./eval_main.py", line 48, in eval_policy
>     obs = env.reset()
>   File "/homes/yangyang/miniconda3/envs/coll/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 44, in reset
>     return self.env.reset()
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/envs/object_env.py", line 326, in reset
>     self.goal = self._sample_goal()
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/envs/object_env.py", line 469, in _sample_goal
>     obs = self._get_obs()
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/envs/object_env.py", line 124, in _get_obs
>     image = self._get_cam_frame().astype(np.float32)
>   File "/homes/yangyang/PycharmProjects/Collections/object_collections/object_collections/envs/base.py", line 54, in _get_cam_frame
>     cam_img = self.sim.render(width, height, camera_name='camera1')[::-1, :, :] # Rendered images are upside-down.
>   File "mujoco_py/mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
>   File "mujoco_py/mjsim.pyx", line 158, in mujoco_py.cymj.MjSim.render
>   File "mujoco_py/mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
>   File "mujoco_py/mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
>   File "mujoco_py/opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
> RuntimeError: Failed to initialize OpenGL
>

**Comment by st2yang** [comment]
I managed to set up bashrc to run the code.

**Comment by madhan001** [comment]
@st2yang what were the exact changes you did to bashrc to fix this error?

**Comment by st2yang** [comment]
@madhan001 This is my modified bashrc

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/homes/yangyang/.mujoco/mujoco200/bin
> export MUJOCO_KEY_PATH=/homes/yangyang/.mujoco${MUJOCO_KEY_PATH}
> export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
